import React,{useEffect,useState} from 'react';
import {View,Text,StyleSheet,TouchableOpacity,SafeAreaView,ScrollView,Alert,ActivityIndicator} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {COLORS} from '../constants';
import {useApp} from '../context/AppContext';
import {fetchAdminStats,fetchAdminOrders,updateAdminOrderStatus,fetchAdminReferrals} from '../services/api';
import FulatanLogo from '../components/FulatanLogo';

export default function AdminDashboardScreen(){
 const navigation=useNavigation<any>(); const {user,language}=useApp();
 const [stats,setStats]=useState({products:0,registeredUsers:0,ordersToday:0,revenue:0}); const [orders,setOrders]=useState<any[]>([]); const [referrals,setReferrals]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [s,o,r]=await Promise.all([fetchAdminStats(),fetchAdminOrders(),fetchAdminReferrals()]);setStats(s);setOrders(o);setReferrals(r);}catch(e:any){Alert.alert('Error',e?.message||'Could not load admin data.');}finally{setLoading(false)}};
 useEffect(()=>{if(user?.role==='admin')load();},[user?.role]);
 if(!user||user.role!=='admin')return <SafeAreaView style={styles.denied}><Text style={styles.deniedTitle}>Admin access required</Text></SafeAreaView>;
 const setStatus=async(id:string,status:string)=>{try{await updateAdminOrderStatus(id,status);await load();}catch(e:any){Alert.alert('Error',e?.message||'Could not update order.')}};
 const money=(n:number)=>`₦${Number(n||0).toLocaleString('en-NG')}`;
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.header}><View style={styles.brandBlock}><FulatanLogo width={78} height={62}/><View><Text style={styles.kicker}>FULATAN</Text><Text style={styles.title}>ADMIN DASHBOARD</Text><Text style={styles.sub}>Marketplace control center</Text></View></View><View style={styles.secure}><Text>🛡️</Text><Text style={styles.secureText}>SECURE</Text></View></View>
  <View style={styles.stats}>{[[stats.products,'Total Products','📦'],[stats.ordersToday,'Orders Today','🧾'],[stats.registeredUsers,'Registered Users','👥'],[money(stats.revenue),'Revenue','₦']].map(([n,l,i])=><View style={styles.stat} key={String(l)}><Text style={styles.icon}>{i}</Text><Text style={styles.num}>{n}</Text><Text style={styles.label}>{l}</Text></View>)}</View>
  <Text style={styles.section}>Quick Actions</Text><View style={styles.actions}><Action title="＋ Add Phone" onPress={()=>navigation.navigate('AddPhone')}/><Action title="▤ Orders" onPress={()=>navigation.navigate('Orders')}/><Action title="⚙ Settings" onPress={()=>navigation.navigate('Settings')}/></View>
  <View style={styles.card}><View style={styles.row}><Text style={styles.section}>Recent Orders</Text><TouchableOpacity onPress={()=>navigation.navigate('Orders')}><Text style={styles.link}>View all</Text></TouchableOpacity></View>{loading?<ActivityIndicator color={COLORS.primary}/>:orders.length===0?<Text style={styles.empty}>No real orders yet.</Text>:orders.slice(0,6).map(o=><View key={o.id} style={styles.order}><View style={{flex:1}}><Text style={styles.orderTitle}>{o.buyerName||'Customer'}</Text><Text style={styles.muted}>{money(o.total)} · {new Date(o.createdAt).toLocaleDateString()}</Text></View><TouchableOpacity onPress={()=>Alert.alert('Order status',`Current: ${o.status}`,['pending','confirmed','processing','shipped','completed','cancelled'].map(s=>({text:s,onPress:()=>setStatus(o.id,s)})))} style={styles.status}><Text style={styles.statusText}>{o.status}</Text></TouchableOpacity></View>)}</View>
  <View style={styles.card}><View style={styles.row}><Text style={styles.section}>Referral Commissions</Text><Text style={styles.link}>{referrals.length} records</Text></View>{referrals.length===0?<Text style={styles.empty}>No referral commission has been generated yet.</Text>:referrals.slice(0,5).map(r=><View style={styles.order} key={r.id}><View style={{flex:1}}><Text style={styles.orderTitle}>{r.referrer_name}</Text><Text style={styles.muted}>{r.phone_title||'Phone'} · {r.status}</Text></View><Text style={styles.amount}>{money(r.amount)}</Text></View>)}</View>
 </ScrollView></SafeAreaView>
}
function Action({title,onPress}:{title:string;onPress:()=>void}){return <TouchableOpacity style={styles.action} onPress={onPress}><Text style={styles.actionText}>{title}</Text></TouchableOpacity>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#070809'},content:{padding:16,paddingBottom:35},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},brandBlock:{flexDirection:'row',alignItems:'center',flex:1},kicker:{fontSize:10,color:'#FF5A14',fontWeight:'900',letterSpacing:2},title:{fontSize:25,fontWeight:'900',color:'#fff',marginTop:2},sub:{fontSize:11,color:'#8F939B',marginTop:3},secure:{backgroundColor:'#102218',padding:10,borderRadius:14,alignItems:'center'},secureText:{fontSize:8,color:'#22C55E',fontWeight:'900',marginTop:2},stats:{flexDirection:'row',flexWrap:'wrap',gap:10},stat:{width:'48.4%',backgroundColor:'#101216',borderRadius:16,padding:14,borderWidth:1,borderColor:'#292C32'},icon:{fontSize:19},num:{fontSize:20,fontWeight:'900',color:'#fff',marginTop:5},label:{fontSize:10,color:'#8F939B',fontWeight:'800',marginTop:2},section:{fontSize:17,fontWeight:'900',color:'#fff',marginBottom:10},actions:{flexDirection:'row',gap:8,marginBottom:18},action:{flex:1,backgroundColor:'#101216',borderRadius:14,borderWidth:1,borderColor:'#292C32',padding:13,alignItems:'center'},actionText:{color:'#FF5A14',fontWeight:'900',fontSize:11},card:{backgroundColor:'#101216',borderRadius:17,borderWidth:1,borderColor:'#292C32',padding:15,marginBottom:15},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},link:{color:'#FF5A14',fontWeight:'900',fontSize:11},order:{flexDirection:'row',alignItems:'center',paddingVertical:11,borderTopWidth:1,borderTopColor:'#24272D'},orderTitle:{color:'#fff',fontWeight:'900',fontSize:12},muted:{color:'#8F939B',fontSize:10,marginTop:3},status:{paddingHorizontal:8,paddingVertical:6,borderRadius:8,backgroundColor:'#20150F'},statusText:{color:'#FF5A14',fontSize:9,fontWeight:'900'},amount:{color:'#22C55E',fontWeight:'900',fontSize:12},empty:{color:'#8F939B',fontSize:11,paddingVertical:12},denied:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#070809'},deniedTitle:{color:'#fff',fontWeight:'900',fontSize:20}});
