import React from 'react';
import {View,Text,StyleSheet,SafeAreaView,FlatList,TouchableOpacity,Image} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {NativeStackNavigationProp} from '@react-navigation/native-stack';
import {COLORS} from '../constants'; import {RootStackParamList} from '../types'; import {useApp} from '../context/AppContext';
type Nav=NativeStackNavigationProp<RootStackParamList>;
export default function CartScreen(){
 const navigation=useNavigation<Nav>(); const {cart,phones,updateCartQty,removeFromCart,cartTotal}=useApp(); const total=cartTotal;
 return <SafeAreaView style={styles.container}><View style={styles.header}><View><Text style={styles.kicker}>FULATAN</Text><Text style={styles.title}>My Cart</Text></View><Text style={styles.secure}>🔒 Secure</Text></View>
 <FlatList data={cart} keyExtractor={x=>x.phoneId} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyIcon}>🛒</Text><Text style={styles.emptyTitle}>Your cart is empty</Text><Text style={styles.emptySub}>Add a phone from the marketplace.</Text><TouchableOpacity style={styles.shop} onPress={()=>navigation.navigate('Home')}><Text style={styles.shopText}>Browse Phones</Text></TouchableOpacity></View>} renderItem={({item})=>{const p=phones.find(x=>x.id===item.phoneId);if(!p)return null;return <View style={styles.item}><Image source={{uri:p.images?.[0]}} style={styles.img}/><View style={{flex:1}}><Text style={styles.itemTitle} numberOfLines={2}>{p.title}</Text><Text style={styles.price}>{`₦${Number(p.price).toLocaleString('en-NG')}`}</Text><View style={styles.row}><TouchableOpacity style={styles.qty} onPress={()=>updateCartQty(p.id,item.quantity-1)}><Text style={styles.qtyText}>−</Text></TouchableOpacity><Text style={styles.qtyNum}>{item.quantity}</Text><TouchableOpacity style={styles.qty} onPress={()=>updateCartQty(p.id,item.quantity+1)}><Text style={styles.qtyText}>＋</Text></TouchableOpacity><TouchableOpacity onPress={()=>removeFromCart(p.id)}><Text style={styles.delete}>⌫</Text></TouchableOpacity></View></View></View>}} ListFooterComponent={cart.length?<View><View style={styles.summary}><Text style={styles.summaryTitle}>Order Summary</Text><Line label="Subtotal" value={`₦${Number(cartTotal).toLocaleString('en-NG')}`}/><Line label="Delivery" value="NO"/><View style={styles.totalLine}><Text style={styles.totalLabel}>Total</Text><Text style={styles.total}>{`₦${Number(total).toLocaleString('en-NG')}`}</Text></View></View><TouchableOpacity style={styles.checkout} onPress={()=>navigation.navigate('Checkout')}><Text style={styles.checkoutText}>Proceed to Checkout</Text></TouchableOpacity></View>:null}/></SafeAreaView>
}
function Line({label,value}:{label:string,value:string}){return <View style={styles.line}><Text style={styles.lineLabel}>{label}</Text><Text style={styles.lineValue}>{value}</Text></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#070809'},header:{paddingHorizontal:18,paddingVertical:13,backgroundColor:'#08090B',flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#1B1D21'},kicker:{fontSize:8,color:'#FF5A14',fontWeight:'900',letterSpacing:2},title:{fontSize:21,fontWeight:'900',color:'#fff',marginTop:2},secure:{fontSize:10,color:'#22C55E',fontWeight:'800'},list:{padding:14,paddingBottom:30},item:{backgroundColor:'#101216',borderRadius:15,padding:10,marginBottom:10,flexDirection:'row',gap:12,borderWidth:1,borderColor:'#2B2E35'},img:{width:86,height:98,borderRadius:12,backgroundColor:'#181A1F'},itemTitle:{fontSize:13,fontWeight:'800',color:'#fff'},price:{fontSize:15,fontWeight:'900',color:'#FF6A24',marginTop:6},row:{flexDirection:'row',alignItems:'center',marginTop:10},qty:{width:29,height:29,borderRadius:8,backgroundColor:'#1B1D22',alignItems:'center',justifyContent:'center'},qtyText:{color:'#fff',fontSize:17},qtyNum:{width:32,textAlign:'center',fontWeight:'800',color:'#fff'},delete:{marginLeft:14,fontSize:18,color:'#FF6A24'},summary:{backgroundColor:'#101216',borderRadius:15,padding:16,marginTop:6,borderWidth:1,borderColor:'#2B2E35'},summaryTitle:{fontSize:16,fontWeight:'900',marginBottom:10,color:'#fff'},line:{flexDirection:'row',justifyContent:'space-between',paddingVertical:6},lineLabel:{color:'#A1A1AA'},lineValue:{fontWeight:'700',color:'#E4E4E7'},totalLine:{borderTopWidth:1,borderTopColor:'#2B2E35',marginTop:6,paddingTop:12,flexDirection:'row',justifyContent:'space-between'},totalLabel:{fontWeight:'900',fontSize:16,color:'#fff'},total:{fontWeight:'900',fontSize:19,color:'#FF6A24'},checkout:{backgroundColor:'#FF5A14',borderRadius:13,padding:15,alignItems:'center',marginTop:14},checkoutText:{color:'#fff',fontWeight:'900',fontSize:14},empty:{alignItems:'center',paddingTop:100},emptyIcon:{fontSize:55},emptyTitle:{fontSize:19,fontWeight:'900',marginTop:10,color:'#fff'},emptySub:{color:'#8F939B',marginTop:5},shop:{backgroundColor:'#FF5A14',borderRadius:12,paddingHorizontal:22,paddingVertical:12,marginTop:18},shopText:{color:'#fff',fontWeight:'900'}});
