import React from 'react';
import { View, Text, StyleSheet, SafeAreaView, FlatList, TouchableOpacity, Image } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { COLORS } from '../constants';
import { RootStackParamList } from '../types';
import { formatPrice } from '../services/mockData';
import { useApp } from '../context/AppContext';

type Nav=NativeStackNavigationProp<RootStackParamList>;
export default function CartScreen(){
 const navigation=useNavigation<Nav>(); const {cart,phones,updateCartQty,removeFromCart,cartTotal}=useApp();
 const delivery:number=0; const total=cartTotal+delivery;
 return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.title}>Cart ({cart.length})</Text><Text style={styles.secure}>🔒 Secure</Text></View>
 <FlatList data={cart} keyExtractor={x=>x.phoneId} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Text style={{fontSize:55}}>🛒</Text><Text style={styles.emptyTitle}>Your cart is empty</Text><Text style={styles.emptySub}>Add a phone from the marketplace.</Text><TouchableOpacity style={styles.shop} onPress={()=>navigation.navigate('Home')}><Text style={styles.shopText}>Browse Phones</Text></TouchableOpacity></View>} renderItem={({item})=>{const p=phones.find(x=>x.id===item.phoneId);if(!p)return null;return <View style={styles.item}><Image source={{uri:p.images?.[0]}} style={styles.img}/><View style={{flex:1}}><Text style={styles.itemTitle} numberOfLines={2}>{p.title}</Text><Text style={styles.price}>{formatPrice(p.price)}</Text><View style={styles.row}><TouchableOpacity style={styles.qty} onPress={()=>updateCartQty(p.id,item.quantity-1)}><Text>−</Text></TouchableOpacity><Text style={styles.qtyNum}>{item.quantity}</Text><TouchableOpacity style={styles.qty} onPress={()=>updateCartQty(p.id,item.quantity+1)}><Text>＋</Text></TouchableOpacity><TouchableOpacity onPress={()=>removeFromCart(p.id)}><Text style={styles.delete}>🗑</Text></TouchableOpacity></View></View></View>}} ListFooterComponent={cart.length? <View><View style={styles.summary}><Text style={styles.summaryTitle}>Order Summary</Text><Line label="Subtotal" value={formatPrice(cartTotal)}/><Line label="Delivery" value={delivery?'₦'+delivery.toLocaleString():'NO'}/><View style={styles.totalLine}><Text style={styles.totalLabel}>Total</Text><Text style={styles.total}>{formatPrice(total)}</Text></View></View><TouchableOpacity style={styles.checkout} onPress={()=>navigation.navigate('Checkout')}><Text style={styles.checkoutText}>Proceed to Checkout</Text></TouchableOpacity></View>:null}/></SafeAreaView>
}
function Line({label,value}:{label:string,value:string}){return <View style={styles.line}><Text style={styles.lineLabel}>{label}</Text><Text style={styles.lineValue}>{value}</Text></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F9FC'},header:{height:62,backgroundColor:'#fff',paddingHorizontal:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#E6EBF2'},title:{fontSize:20,fontWeight:'900'},secure:{fontSize:11,color:'#15803D',fontWeight:'800'},list:{padding:14,paddingBottom:30},item:{backgroundColor:'#fff',borderRadius:16,padding:10,marginBottom:10,flexDirection:'row',gap:12,borderWidth:1,borderColor:'#E7ECF3'},img:{width:92,height:105,borderRadius:12,backgroundColor:'#F1F5F9'},itemTitle:{fontSize:14,fontWeight:'800',color:COLORS.black},price:{fontSize:15,fontWeight:'900',color:COLORS.primary,marginTop:6},row:{flexDirection:'row',alignItems:'center',marginTop:10},qty:{width:30,height:30,borderRadius:9,backgroundColor:'#F1F5F9',alignItems:'center',justifyContent:'center'},qtyNum:{width:34,textAlign:'center',fontWeight:'800'},delete:{marginLeft:14,fontSize:18},summary:{backgroundColor:'#fff',borderRadius:16,padding:16,marginTop:6,borderWidth:1,borderColor:'#E7ECF3'},summaryTitle:{fontSize:16,fontWeight:'900',marginBottom:12},line:{flexDirection:'row',justifyContent:'space-between',paddingVertical:6},lineLabel:{color:COLORS.gray},lineValue:{fontWeight:'700'},totalLine:{borderTopWidth:1,borderTopColor:'#E7ECF3',marginTop:6,paddingTop:12,flexDirection:'row',justifyContent:'space-between'},totalLabel:{fontWeight:'900',fontSize:16},total:{fontWeight:'900',fontSize:19,color:COLORS.primary},checkout:{backgroundColor:COLORS.primary,borderRadius:14,padding:16,alignItems:'center',marginTop:14},checkoutText:{color:'#fff',fontWeight:'900',fontSize:15},empty:{alignItems:'center',paddingTop:100},emptyTitle:{fontSize:19,fontWeight:'900',marginTop:10},emptySub:{color:COLORS.gray,marginTop:5},shop:{backgroundColor:COLORS.primary,borderRadius:12,paddingHorizontal:22,paddingVertical:12,marginTop:18},shopText:{color:'#fff',fontWeight:'900'}});
