import React,{useMemo} from 'react';
import {View,Text,StyleSheet,SafeAreaView,FlatList,TouchableOpacity} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {NativeStackNavigationProp} from '@react-navigation/native-stack';
import {COLORS} from '../constants';
import {RootStackParamList} from '../types';
import {useApp} from '../context/AppContext';
import BrandIcon from '../components/BrandIcon';
export default function CategoriesScreen(){
 const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const {phones,categories,language}=useApp();
 const available=useMemo(()=>categories,[categories]); const t=language==='ha';
 return <SafeAreaView style={styles.container}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={()=>navigation.goBack()}><Text style={styles.backText}>‹</Text></TouchableOpacity><View><Text style={styles.kicker}>FULATAN</Text><Text style={styles.title}>Categories</Text></View><View style={{width:42}}/></View>
 <FlatList data={available} numColumns={2} keyExtractor={x=>x.id} contentContainerStyle={styles.grid} showsVerticalScrollIndicator={false} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyF}>F</Text><Text style={styles.emptyTitle}>{t?'Babu category tukuna':'No categories yet'}</Text><Text style={styles.emptySub}>{t?'Categories za bayyana ne bayan Admin ya saka waya.':'Categories appear only after the Admin publishes phones.'}</Text></View>} renderItem={({item})=>{const count=phones.filter(x=>x.brand===item.name).length;return <TouchableOpacity style={styles.card} activeOpacity={.9} onPress={()=>navigation.navigate('Home')}><View style={styles.pic}><BrandIcon brand={item.name} size={74}/></View><Text style={styles.brand}>{item.name}</Text><Text style={styles.count}>{count} {count===1?'item':'items'}</Text><View style={styles.arrow}><Text>›</Text></View></TouchableOpacity>}}/>
 </SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#070809'},header:{backgroundColor:'#08090B',paddingHorizontal:15,paddingVertical:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#1B1D21'},back:{width:40,height:40,borderRadius:13,backgroundColor:'#15171B',alignItems:'center',justifyContent:'center'},backText:{fontSize:32,color:'#fff'},kicker:{fontSize:8,color:'#FF5A14',fontWeight:'900',letterSpacing:2,textAlign:'center'},title:{fontSize:20,fontWeight:'900',color:'#fff',marginTop:1},grid:{padding:8,paddingBottom:30},card:{flex:1,backgroundColor:'#101216',borderRadius:16,margin:6,padding:11,borderWidth:1,borderColor:'#2B2E35',minHeight:175},pic:{height:112,borderRadius:13,backgroundColor:'#17191E',alignItems:'center',justifyContent:'center'},brand:{fontSize:15,fontWeight:'900',marginTop:10,color:'#fff'},count:{fontSize:10,color:'#8F939B',marginTop:3,fontWeight:'800'},arrow:{position:'absolute',right:11,bottom:11,width:25,height:25,borderRadius:8,backgroundColor:'#20150F',alignItems:'center',justifyContent:'center'},empty:{alignItems:'center',padding:55},emptyF:{width:75,height:75,borderRadius:22,backgroundColor:'#111318',color:'#FF5A14',fontSize:45,fontWeight:'900',textAlign:'center',textAlignVertical:'center'},emptyTitle:{fontSize:18,fontWeight:'900',marginTop:14,color:'#fff'},emptySub:{fontSize:11,color:'#8F939B',textAlign:'center',lineHeight:17,marginTop:6}});
