import React,{useState} from 'react';
import { View, Text, StyleSheet, SafeAreaView, ScrollView, TouchableOpacity, TextInput, Alert } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { COLORS } from '../constants';
import { useApp } from '../context/AppContext';
import { formatPrice } from '../services/mockData';
import { createOrder } from '../services/api';
export default function CheckoutScreen(){
 const navigation=useNavigation(); const {cartTotal,clearCart,user,cart}=useApp(); const [method,setMethod]=useState<'delivery'|'pickup'>('delivery'); const [address,setAddress]=useState('');
 const [loading,setLoading]=useState(false); const place=async()=>{if(!user){Alert.alert('Login required','Please login before checkout.');return;}if(method==='delivery'&&!address.trim()){Alert.alert('Address required','Enter your delivery address.');return;}setLoading(true);try{const result=await createOrder(cart,address.trim(),user.phone);Alert.alert('Order received',`Order #${String(result.id).slice(0,8)} has been created successfully.`,[{text:'OK',onPress:()=>{clearCart();navigation.goBack();}}]);}catch(e:any){Alert.alert('Order failed',e?.message||'Could not create order.');}finally{setLoading(false);}};
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Checkout</Text><View style={styles.secure}><Text>🔒 Secure checkout</Text><Text style={styles.green}>Admin-controlled marketplace</Text></View><Text style={styles.section}>Delivery method</Text><View style={styles.methods}><TouchableOpacity style={[styles.method,method==='delivery'&&styles.active]} onPress={()=>setMethod('delivery')}><Text style={{fontSize:22}}>🚚</Text><Text style={styles.methodTitle}>Delivery</Text><Text style={styles.methodSub}>To your address</Text></TouchableOpacity><TouchableOpacity style={[styles.method,method==='pickup'&&styles.active]} onPress={()=>setMethod('pickup')}><Text style={{fontSize:22}}>🏪</Text><Text style={styles.methodTitle}>Office Pickup</Text><Text style={styles.methodSub}>Collect from office</Text></TouchableOpacity></View>{method==='delivery'&&<><Text style={styles.section}>Delivery address</Text><TextInput value={address} onChangeText={setAddress} placeholder="House, street, area, state" placeholderTextColor={COLORS.gray} style={styles.input}/></>}<Text style={styles.section}>Payment</Text><View style={styles.payment}><Text style={{fontSize:22}}>💳</Text><View style={{flex:1,marginLeft:10}}><Text style={styles.methodTitle}>Online payment</Text><Text style={styles.methodSub}>Flutterwave will be connected securely through the backend.</Text></View><Text>›</Text></View><View style={styles.summary}><Text style={styles.summaryTitle}>Order total</Text><Text style={styles.total}>{formatPrice(cartTotal)}</Text></View><TouchableOpacity style={[styles.place,loading&&{opacity:.6}]} onPress={place} disabled={loading}><Text style={styles.placeText}>{loading?'Creating Order...':'Place Order'}</Text></TouchableOpacity></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F9FC'},content:{padding:18,paddingBottom:40},title:{fontSize:25,fontWeight:'900',color:COLORS.black},secure:{backgroundColor:'#ECFDF5',borderRadius:12,padding:12,marginTop:12},green:{color:'#15803D',fontSize:11,fontWeight:'700',marginTop:3},section:{fontSize:16,fontWeight:'900',marginTop:22,marginBottom:10},methods:{flexDirection:'row',gap:10},method:{flex:1,backgroundColor:'#fff',borderRadius:15,padding:14,borderWidth:1,borderColor:'#E3E9F1'},active:{borderColor:COLORS.primary,backgroundColor:'#EFF6FF'},methodTitle:{fontWeight:'900',marginTop:5},methodSub:{fontSize:11,color:COLORS.gray,marginTop:3},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#E2E8F0',borderRadius:13,padding:14,fontSize:14,color:COLORS.black},payment:{backgroundColor:'#fff',borderRadius:15,padding:15,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#E3E9F1'},summary:{backgroundColor:'#fff',borderRadius:15,padding:16,marginTop:20,flexDirection:'row',justifyContent:'space-between'},summaryTitle:{fontWeight:'900',fontSize:16},total:{fontSize:20,fontWeight:'900',color:COLORS.primary},place:{backgroundColor:COLORS.primary,borderRadius:14,padding:16,alignItems:'center',marginTop:14},placeText:{color:'#fff',fontWeight:'900',fontSize:15}});
