import React,{useEffect,useState} from 'react';
import {View,Text,StyleSheet,SafeAreaView,ScrollView,TouchableOpacity,TextInput,Alert,Linking,ActivityIndicator} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {COLORS,NIGERIAN_STATES} from '../constants';
import {useApp} from '../context/AppContext';
import {createOrder} from '../services/api';

export default function CheckoutScreen(){
 const navigation=useNavigation(); const {cartTotal,clearCart,user,cart,language}=useApp();
 const [method,setMethod]=useState<'delivery'|'pickup'>('delivery');
 const [name,setName]=useState(user?.name||''); const [email,setEmail]=useState(user?.email||''); const [phone,setPhone]=useState(user?.phone||'');
 const [address,setAddress]=useState(''); const [state,setState]=useState(''); const [lga,setLga]=useState(''); const [landmark,setLandmark]=useState(''); const [loading,setLoading]=useState(false);
 useEffect(()=>{setName(user?.name||'');setEmail(user?.email||'');setPhone(user?.phone||'')},[user]);
 const place=async()=>{
  if(!user){Alert.alert('Login required','Please login before checkout.');return;}
  if(!name.trim()||!email.trim()||!phone.trim()||!state.trim()||!lga.trim()||(method==='delivery'&&!address.trim())){Alert.alert(language==='ha'?'Cika bayanai':'Complete details',language==='ha'?'Cika sunanka, email, lambar waya, jiha, LGA da adireshi.':'Complete your name, email, phone, state, LGA and delivery address.');return;}
  if(email.trim().toLowerCase()!==user.email.toLowerCase()){Alert.alert('Account email required','Use the email attached to your FULATAN account.');return;}
  setLoading(true);
  try{const result=await createOrder(cart,{deliveryAddress:method==='pickup'?'Office Pickup':address.trim(),phoneNumber:phone.trim(),buyerName:name.trim(),buyerEmail:email.trim(),deliveryState:state.trim(),deliveryLga:lga.trim(),deliveryLandmark:landmark.trim(),deliveryMethod:method});if(result.paymentLink){clearCart();await Linking.openURL(result.paymentLink);}else Alert.alert('Payment unavailable','The payment gateway did not return a payment link.');}
  catch(e:any){Alert.alert('Order failed',e?.message||'Could not create order.');}finally{setLoading(false)}
 };
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{language==='ha'?'Biyan Kudi':'Checkout'}</Text><View style={styles.secure}><Text style={styles.secureTitle}>🔒 {language==='ha'?'Biyan kudi cikin tsaro':'Secure checkout'}</Text><Text style={styles.green}>{language==='ha'?'Bayanan order ɗinka za a adana su tare da order.':'Your customer details are saved with this order.'}</Text></View>
 <Text style={styles.section}>{language==='ha'?'Bayanan Customer':'Customer details'}</Text>
 <Text style={styles.label}>Full Name</Text><TextInput value={name} onChangeText={setName} style={styles.input} placeholder="Your full name" placeholderTextColor={COLORS.gray}/>
 <Text style={styles.label}>Account Email</Text><TextInput value={email} onChangeText={setEmail} editable={false} style={[styles.input,styles.disabled]} placeholder="you@email.com" placeholderTextColor={COLORS.gray}/>
 <Text style={styles.label}>Phone Number</Text><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" style={styles.input} placeholder="08012345678" placeholderTextColor={COLORS.gray}/>
 <Text style={styles.section}>{language==='ha'?'Hanyar karɓa':'Fulfilment'}</Text><View style={styles.methods}><TouchableOpacity style={[styles.method,method==='delivery'&&styles.active]} onPress={()=>setMethod('delivery')}><Text style={{fontSize:22}}>🚚</Text><Text style={styles.methodTitle}>Delivery</Text><Text style={styles.methodSub}>To your address</Text></TouchableOpacity><TouchableOpacity style={[styles.method,method==='pickup'&&styles.active]} onPress={()=>setMethod('pickup')}><Text style={{fontSize:22}}>🏪</Text><Text style={styles.methodTitle}>Office Pickup</Text><Text style={styles.methodSub}>Collect from office</Text></TouchableOpacity></View>
 <Text style={styles.section}>{language==='ha'?'Wurin karɓa':'Delivery details'}</Text>
 <Text style={styles.label}>State</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.stateRow}>{NIGERIAN_STATES.map(x=><TouchableOpacity key={x} onPress={()=>setState(x)} style={[styles.stateChip,state===x&&styles.stateActive]}><Text style={[styles.stateText,state===x&&styles.stateTextActive]}>{x}</Text></TouchableOpacity>)}</ScrollView>
 <Text style={styles.label}>LGA</Text><TextInput value={lga} onChangeText={setLga} style={styles.input} placeholder="e.g. Dawakin Tofa" placeholderTextColor={COLORS.gray}/>
 {method==='delivery'&&<><Text style={styles.label}>Address</Text><TextInput value={address} onChangeText={setAddress} multiline style={[styles.input,styles.multiline]} placeholder="House number, street, area" placeholderTextColor={COLORS.gray}/></>}
 <Text style={styles.label}>Landmark (optional)</Text><TextInput value={landmark} onChangeText={setLandmark} style={styles.input} placeholder="Nearby landmark" placeholderTextColor={COLORS.gray}/>
 <Text style={styles.section}>{language==='ha'?'Biya':'Payment'}</Text><View style={styles.payment}><Text style={{fontSize:22}}>💳</Text><View style={{flex:1,marginLeft:10}}><Text style={styles.methodTitle}>Online payment</Text><Text style={styles.methodSub}>Secure payment via Flutterwave.</Text></View></View>
 <View style={styles.summary}><Text style={styles.summaryTitle}>Order total</Text><Text style={styles.total}>{`₦${Number(cartTotal).toLocaleString('en-NG')}`}</Text></View><TouchableOpacity style={[styles.place,loading&&{opacity:.6}]} onPress={place} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.placeText}>{language==='ha'?'Ci gaba zuwa biyan kudi':'Continue to payment'}</Text>}</TouchableOpacity></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#070809'},content:{padding:18,paddingBottom:50},title:{fontSize:25,fontWeight:'900',color:'#fff'},secure:{backgroundColor:'#102218',borderRadius:12,padding:12,marginTop:12},secureTitle:{color:'#fff',fontWeight:'900'},green:{color:'#22C55E',fontSize:11,fontWeight:'700',marginTop:3},section:{fontSize:16,fontWeight:'900',color:'#fff',marginTop:22,marginBottom:10},label:{fontSize:13,fontWeight:'800',color:'#fff',marginBottom:6},input:{backgroundColor:'#101216',borderWidth:1,borderColor:'#2B2E35',borderRadius:13,padding:14,fontSize:14,color:'#fff',marginBottom:12},disabled:{opacity:.7},multiline:{minHeight:90,textAlignVertical:'top'},methods:{flexDirection:'row',gap:10},method:{flex:1,backgroundColor:'#101216',borderRadius:15,padding:14,borderWidth:1,borderColor:'#2B2E35'},active:{borderColor:'#FF5A14',backgroundColor:'#20150F'},methodTitle:{fontWeight:'900',color:'#fff',marginTop:5},methodSub:{fontSize:11,color:'#A1A1AA',marginTop:3},stateRow:{gap:8,paddingBottom:12},stateChip:{paddingHorizontal:12,paddingVertical:10,borderRadius:20,borderWidth:1,borderColor:'#2B2E35',backgroundColor:'#101216'},stateActive:{backgroundColor:'#FF5A14',borderColor:'#FF5A14'},stateText:{color:'#A1A1AA',fontWeight:'700',fontSize:12},stateTextActive:{color:'#fff'},payment:{backgroundColor:'#101216',borderRadius:15,padding:15,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#2B2E35'},summary:{backgroundColor:'#101216',borderRadius:15,padding:16,marginTop:20,flexDirection:'row',justifyContent:'space-between'},summaryTitle:{fontWeight:'900',fontSize:16,color:'#fff'},total:{fontSize:20,fontWeight:'900',color:COLORS.primary},place:{backgroundColor:COLORS.primary,borderRadius:14,padding:16,alignItems:'center',marginTop:14},placeText:{color:'#fff',fontWeight:'900',fontSize:15}});
