import React from 'react';
import { View, Text, StyleSheet, ScrollView, Image, TouchableOpacity, Linking, SafeAreaView, Alert } from 'react-native';
import { useRoute, useNavigation, RouteProp } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from '../types';
import { COLORS } from '../constants';
import { useApp } from '../context/AppContext';
import { formatPrice } from '../services/mockData';
import { createOrGetChat } from '../services/api';

type Route=RouteProp<RootStackParamList,'PhoneDetails'>; type Nav=NativeStackNavigationProp<RootStackParamList>;
export default function PhoneDetailsScreen(){
 const route=useRoute<Route>();const navigation=useNavigation<Nav>();const {phones,user,isFavorite,toggleFavorite,contactSettings,language,addToCart}=useApp();const phone=phones.find(p=>p.id===route.params.phoneId);
 if(!phone)return <View style={styles.center}><Text>Phone not found</Text></View>;
 const fav=isFavorite(phone.id);const adminNumber=contactSettings.phone||phone.sellerPhone;const wa=contactSettings.whatsapp||phone.sellerPhone;
 const call=()=>{if(!contactSettings.callEnabled){Alert.alert('Call unavailable','Admin has disabled call contact.');return;}Linking.openURL(`tel:${adminNumber}`)};
 const whatsapp=()=>{if(!contactSettings.whatsappEnabled){Alert.alert('WhatsApp unavailable','Admin has disabled WhatsApp contact.');return;}const n=wa.replace(/[^0-9]/g,'');const norm=n.startsWith('234')?n:`234${n.replace(/^0+/,'')}`;Linking.openURL(`https://wa.me/${norm}?text=${encodeURIComponent(`Sannu FULATAN, ina sha'awar ${phone.title}`)}`)};
 const chat=async()=>{if(!contactSettings.chatEnabled){Alert.alert('Chat unavailable','Admin has disabled in-app chat.');return;}if(!user){navigation.navigate('Login');return;}try{const id=await createOrGetChat(phone.id,phone.title,user.id,phone.sellerId);navigation.navigate('Chat',{chatId:id,phoneTitle:phone.title,otherUserName:'FULATAN COMMUNICATION'});}catch{navigation.navigate('Chat',{chatId:`admin_${phone.id}_${user.id}`,phoneTitle:phone.title,otherUserName:'FULATAN COMMUNICATION'});}};
 return <SafeAreaView style={styles.container}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:110}}><View style={styles.photo}><Image source={{uri:phone.images?.[0]}} style={styles.image}/><TouchableOpacity style={styles.back} onPress={()=>navigation.goBack()}><Text style={styles.backText}>‹</Text></TouchableOpacity><TouchableOpacity style={styles.favorite} onPress={()=>toggleFavorite(phone.id)}><Text style={{fontSize:20}}>{fav?'❤️':'♡'}</Text></TouchableOpacity></View><View style={styles.content}><View style={styles.topLine}><View style={styles.badge}><Text style={styles.badgeText}>{phone.brand}</Text></View><Text style={styles.price}>{formatPrice(phone.price)}</Text></View><Text style={styles.title}>{phone.title}</Text><View style={styles.meta}><Text>⌖ {phone.location}, {phone.state}</Text><Text>• {phone.condition}</Text></View><View style={styles.specs}><Spec label="Storage" value={phone.title.match(/\d+GB/i)?.[0]||'—'}/><Spec label="Condition" value={phone.condition}/><Spec label="Views" value={String(phone.views||0)}/><Spec label="Seller" value="Verified"/></View><Text style={styles.section}>Description</Text><Text style={styles.description}>{phone.description}</Text><View style={styles.seller}><View style={styles.sellerLogo}><Text style={{fontSize:20,fontWeight:'900',color:COLORS.primary}}>F</Text></View><View style={{flex:1}}><Text style={styles.sellerName}>FULATAN COMMUNICATION</Text><Text style={styles.sellerSub}>✓ Verified Seller · ⭐ {phone.sellerRating.toFixed(1)}</Text></View><Text style={styles.chev}>›</Text></View><Text style={styles.adminNote}>Call, WhatsApp and Chat are controlled by FULATAN Admin.</Text></View></ScrollView><View style={styles.bottom}><View style={styles.contactRow}>{contactSettings.callEnabled&&<TouchableOpacity style={styles.outlineBtn} onPress={call}><Text>📞</Text><Text style={styles.outlineText}>Call</Text></TouchableOpacity>}{contactSettings.whatsappEnabled&&<TouchableOpacity style={styles.waBtn} onPress={whatsapp}><Text style={{fontSize:17}}>🟢</Text><Text style={styles.waText}>WhatsApp</Text></TouchableOpacity>}{contactSettings.chatEnabled&&<TouchableOpacity style={styles.chatBtn} onPress={chat}><Text>💬</Text><Text style={styles.chatText}>Chat</Text></TouchableOpacity>}</View><TouchableOpacity style={styles.buy} onPress={()=>{addToCart(phone.id);navigation.navigate('Cart')}}><Text style={styles.buyText}>Buy Now</Text></TouchableOpacity></View></SafeAreaView>
}
function Spec({label,value}:{label:string,value:string}){return <View style={styles.spec}><Text style={{fontSize:18}}>▣</Text><Text style={styles.specLabel}>{value}</Text><Text style={styles.specSub}>{label}</Text></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#fff'},photo:{height:340,backgroundColor:'#F1F5F9',position:'relative'},image:{width:'100%',height:'100%',resizeMode:'cover'},back:{position:'absolute',left:15,top:18,width:40,height:40,borderRadius:20,backgroundColor:'rgba(255,255,255,.94)',alignItems:'center',justifyContent:'center'},backText:{fontSize:34,lineHeight:35},favorite:{position:'absolute',right:15,top:18,width:40,height:40,borderRadius:20,backgroundColor:'rgba(255,255,255,.94)',alignItems:'center',justifyContent:'center'},content:{padding:18},topLine:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},badge:{backgroundColor:COLORS.primary,borderRadius:8,paddingHorizontal:9,paddingVertical:5},badgeText:{color:'#fff',fontWeight:'900',fontSize:10},price:{fontSize:21,fontWeight:'900',color:'#E85D04'},title:{fontSize:22,fontWeight:'900',color:COLORS.black,marginTop:10},meta:{flexDirection:'row',gap:12,color:COLORS.gray,marginTop:8},specs:{flexDirection:'row',marginTop:18,backgroundColor:'#F8FAFC',borderRadius:14,padding:12},spec:{flex:1,alignItems:'center'},specLabel:{fontWeight:'900',fontSize:11,marginTop:4},specSub:{fontSize:9,color:COLORS.gray,marginTop:2},section:{fontSize:17,fontWeight:'900',marginTop:20,marginBottom:7},description:{fontSize:13,color:'#475569',lineHeight:20},seller:{marginTop:18,borderWidth:1,borderColor:'#E5EAF1',borderRadius:14,padding:12,flexDirection:'row',alignItems:'center'},sellerLogo:{width:44,height:44,borderRadius:12,backgroundColor:'#EFF6FF',alignItems:'center',justifyContent:'center',marginRight:10},sellerName:{fontWeight:'900'},sellerSub:{fontSize:11,color:'#15803D',marginTop:4},chev:{fontSize:25,color:COLORS.gray},adminNote:{fontSize:11,color:COLORS.gray,marginTop:12,textAlign:'center'},bottom:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#E5EAF1',padding:10},contactRow:{flexDirection:'row',gap:7},outlineBtn:{flex:1,borderWidth:1,borderColor:COLORS.primary,borderRadius:11,padding:10,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:5},outlineText:{fontWeight:'800',color:COLORS.primary,fontSize:11},waBtn:{flex:1,backgroundColor:'#DCFCE7',borderRadius:11,padding:10,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:5},waText:{fontWeight:'800',color:'#15803D',fontSize:11},chatBtn:{flex:1,backgroundColor:'#EFF6FF',borderRadius:11,padding:10,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:5},chatText:{fontWeight:'800',color:COLORS.primary,fontSize:11},buy:{marginTop:8,backgroundColor:COLORS.primary,borderRadius:12,padding:14,alignItems:'center'},buyText:{color:'#fff',fontWeight:'900',fontSize:16},center:{flex:1,alignItems:'center',justifyContent:'center'}});
