import React from 'react';
import {View,Text,StyleSheet,TouchableOpacity,SafeAreaView,Alert,ScrollView} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {COLORS} from '../constants';
import {useApp} from '../context/AppContext';
import {logoutUser} from '../services/api';

export default function ProfileScreen(){
 const navigation=useNavigation<any>(); const {user,setUser,isAdmin,language,setLanguage,favorites,cartCount}=useApp();
 const logout=()=>Alert.alert(language==='ha'?'Fita':'Logout',language==='ha'?'Kana son fita?':'Are you sure you want to logout?',[{text:language==='ha'?'Soke':'Cancel',style:'cancel'},{text:language==='ha'?'Fita':'Logout',style:'destructive',onPress:async()=>{await logoutUser().catch(()=>{});setUser(null)}}]);
 if(!user) return <SafeAreaView style={styles.container}><View style={styles.guest}><View style={styles.logo}><Text style={styles.logoF}>F</Text><View style={styles.dot}/></View><Text style={styles.guestTitle}>FULATAN COMMUNICATION</Text><Text style={styles.guestSub}>{language==='ha'?'Sayi • Tuntuɓa • Amincewa':'Buy • Connect • Trust'}</Text><TouchableOpacity style={styles.primary} onPress={()=>navigation.navigate('Login')}><Text style={styles.primaryText}>{language==='ha'?'Shiga':'Sign In'}</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={()=>navigation.navigate('Register')}><Text style={styles.secondaryText}>{language==='ha'?'Yi Rajista':'Create Account'}</Text></TouchableOpacity></View></SafeAreaView>;
 const menu=[['📦',language==='ha'?'Odarori na':'My Orders',language==='ha'?'Bibiyar odar ka':'Orders and delivery tracking',()=>{}],['♥',language==='ha'?'Favorites':'My Favorites',`${favorites.length} saved phones`,()=>navigation.navigate('Favorites')],['💬',language==='ha'?'Hirarraki':'My Chats','FULATAN Admin support',()=>navigation.navigate('Chat',{chatId:'admin_support',phoneTitle:'FULATAN Support',otherUserName:'FULATAN COMMUNICATION'})],['🌐',`Language: ${language==='ha'?'Hausa':'English'}`,'Tap to switch language',()=>setLanguage(language==='ha'?'en':'ha')],['⚙',language==='ha'?'Saituna':'Settings','Account and app settings',()=>{}]] as const;
 return <SafeAreaView style={styles.container}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:105}}><View style={styles.head}><View style={styles.logo}><Text style={styles.logoF}>{user.name.charAt(0).toUpperCase()}</Text><View style={styles.dot}/></View><Text style={styles.name}>{user.name}</Text><Text style={styles.phone}>{user.phone}</Text><View style={styles.stats}><View><Text style={styles.statNum}>{favorites.length}</Text><Text style={styles.statLabel}>Favorites</Text></View><View><Text style={styles.statNum}>{cartCount}</Text><Text style={styles.statLabel}>Cart</Text></View><View><Text style={styles.statNum}>{user.totalSales||0}</Text><Text style={styles.statLabel}>Sales</Text></View></View>{isAdmin&&<View style={styles.adminPill}><Text style={styles.adminText}>🛡 FULATAN ADMIN</Text></View>}</View>
 <View style={styles.menu}>{isAdmin&&<TouchableOpacity style={styles.adminCard} onPress={()=>navigation.navigate('AdminDashboard')}><View style={styles.adminIcon}><Text>🛡</Text></View><View style={{flex:1}}><Text style={styles.itemTitle}>Admin Dashboard</Text><Text style={styles.itemSub}>Manage phones, publishing and contacts</Text></View><Text style={styles.chev}>›</Text></TouchableOpacity>}{menu.map(([i,t,s,on])=><TouchableOpacity key={t} style={styles.menuItem} onPress={on}><View style={styles.iconBox}><Text style={styles.icon}>{i}</Text></View><View style={{flex:1}}><Text style={styles.itemTitle}>{t}</Text><Text style={styles.itemSub}>{s}</Text></View><Text style={styles.chev}>›</Text></TouchableOpacity>)}<TouchableOpacity style={styles.logout} onPress={logout}><Text style={styles.logoutIcon}>⇥</Text><View><Text style={styles.logoutTitle}>{language==='ha'?'Fita':'Logout'}</Text><Text style={styles.itemSub}>Sign out securely</Text></View></TouchableOpacity></View></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},guest:{flex:1,alignItems:'center',justifyContent:'center',padding:24},logo:{width:88,height:88,borderRadius:27,backgroundColor:COLORS.navy,alignItems:'center',justifyContent:'center',shadowColor:COLORS.primary,shadowOpacity:.25,shadowRadius:16,elevation:8},logoF:{fontSize:54,fontWeight:'900',color:'#60A5FA'},dot:{position:'absolute',right:9,bottom:9,width:11,height:11,borderRadius:6,backgroundColor:COLORS.accent},guestTitle:{fontSize:24,fontWeight:'900',color:COLORS.black,marginTop:18},guestSub:{color:COLORS.gray,marginTop:5,fontWeight:'700'},primary:{backgroundColor:COLORS.primary,borderRadius:15,width:'88%',padding:15,alignItems:'center',marginTop:28},primaryText:{color:'#fff',fontWeight:'900',fontSize:15},secondary:{borderWidth:1.5,borderColor:COLORS.primary,borderRadius:15,width:'88%',padding:14,alignItems:'center',marginTop:10},secondaryText:{color:COLORS.primary,fontWeight:'900'},head:{backgroundColor:COLORS.navy,alignItems:'center',paddingTop:28,paddingBottom:22,borderBottomLeftRadius:28,borderBottomRightRadius:28},name:{fontSize:23,fontWeight:'900',color:'#fff',marginTop:11},phone:{color:'#B9C5D8',marginTop:3,fontWeight:'700'},stats:{marginTop:18,flexDirection:'row',gap:38},statNum:{fontSize:18,fontWeight:'900',color:'#fff',textAlign:'center'},statLabel:{fontSize:9,color:'#AEBBD0',fontWeight:'800',marginTop:2,textAlign:'center'},adminPill:{marginTop:13,backgroundColor:'#DCFCE7',paddingHorizontal:12,paddingVertical:6,borderRadius:20},adminText:{fontSize:9,color:'#166534',fontWeight:'900'},menu:{marginTop:14,backgroundColor:'#fff',borderTopWidth:1,borderBottomWidth:1,borderColor:COLORS.border},adminCard:{margin:12,padding:13,borderRadius:17,backgroundColor:'#EAF1FF',flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#BFD2FF'},adminIcon:{width:42,height:42,borderRadius:13,backgroundColor:COLORS.primary,alignItems:'center',justifyContent:'center',marginRight:10},menuItem:{minHeight:74,flexDirection:'row',alignItems:'center',paddingHorizontal:15,borderTopWidth:1,borderTopColor:'#EDF1F6'},iconBox:{width:42,height:42,borderRadius:13,backgroundColor:'#F2F5F9',alignItems:'center',justifyContent:'center',marginRight:10},icon:{fontSize:19},itemTitle:{fontSize:14,fontWeight:'900',color:COLORS.black},itemSub:{fontSize:10,color:COLORS.gray,marginTop:3,fontWeight:'600'},chev:{fontSize:27,color:'#9AA6B8'},logout:{margin:12,padding:13,borderRadius:16,backgroundColor:'#FFF1F1',flexDirection:'row',alignItems:'center'},logoutIcon:{fontSize:25,color:'#DC2626',marginRight:12},logoutTitle:{fontSize:14,fontWeight:'900',color:'#DC2626'}});
