import React from 'react';
import { View,Text,StyleSheet,TouchableOpacity,SafeAreaView,Alert,ScrollView } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { COLORS } from '../constants';
import { useApp } from '../context/AppContext';
import { logoutUser } from '../services/firebaseService';
export default function ProfileScreen(){
 const navigation=useNavigation<any>();const {user,setUser,isAdmin,language,setLanguage}=useApp();
 const logout=()=>Alert.alert('Logout','Are you sure you want to logout?',[{text:'Cancel',style:'cancel'},{text:'Logout',style:'destructive',onPress:async()=>{await logoutUser().catch(()=>{});setUser(null)}}]);
 if(!user)return <SafeAreaView style={styles.container}><View style={styles.guest}><View style={styles.logo}><Text style={styles.logoF}>F</Text><Text style={styles.logoCart}>🛒</Text></View><Text style={styles.guestTitle}>FULATAN COMMUNICATION</Text><Text style={styles.guestSub}>Buy · Sell · Upgrade</Text><TouchableOpacity style={styles.login} onPress={()=>navigation.navigate('Login')}><Text style={styles.loginText}>Sign In</Text></TouchableOpacity><TouchableOpacity style={styles.register} onPress={()=>navigation.navigate('Register')}><Text style={styles.registerText}>Create Account</Text></TouchableOpacity></View></SafeAreaView>;
 const menu=[['📦','My Orders','Orders and delivery tracking',()=>{}],['❤️','My Favorites','Saved phones',()=>navigation.navigate('Favorites')],['💬','My Chats','Talk to FULATAN Admin',()=>navigation.navigate('Chat',{chatId:'admin_support',phoneTitle:'FULATAN Support',otherUserName:'FULATAN COMMUNICATION'})],['🌐',`Language: ${language==='ha'?'Hausa':'English'}`,'Switch language',()=>setLanguage(language==='ha'?'en':'ha')],['⚙️','Settings','Account and app settings',()=>{}]] as const;
 return <SafeAreaView style={styles.container}><ScrollView showsVerticalScrollIndicator={false}><View style={styles.profileHead}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.charAt(0).toUpperCase()}</Text></View><Text style={styles.name}>{user.name}</Text><Text style={styles.phone}>{user.phone}</Text><Text style={styles.rating}>⭐ {(user.rating||5).toFixed(1)} · {user.totalSales||0} sales</Text>{isAdmin&&<View style={styles.adminPill}><Text style={styles.adminText}>🛡️ FULATAN ADMIN</Text></View>}</View><View style={styles.menu}>{isAdmin&&<TouchableOpacity style={styles.menuItem} onPress={()=>navigation.navigate('AdminDashboard')}><Text style={styles.icon}>🛡️</Text><View style={{flex:1}}><Text style={styles.itemTitle}>Admin Dashboard</Text><Text style={styles.itemSub}>Manage products, contacts, orders & security</Text></View><Text style={styles.chev}>›</Text></TouchableOpacity>}{menu.map(([i,t,s,on])=><TouchableOpacity key={t} style={styles.menuItem} onPress={on}><Text style={styles.icon}>{i}</Text><View style={{flex:1}}><Text style={styles.itemTitle}>{t}</Text><Text style={styles.itemSub}>{s}</Text></View><Text style={styles.chev}>›</Text></TouchableOpacity>)}<TouchableOpacity style={[styles.menuItem,styles.logout]} onPress={logout}><Text style={styles.icon}>🚪</Text><View style={{flex:1}}><Text style={[styles.itemTitle,{color:'#DC2626'}]}>Logout</Text><Text style={styles.itemSub}>Sign out securely</Text></View></TouchableOpacity></View></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F9FC'},guest:{flex:1,alignItems:'center',justifyContent:'center',padding:24},logo:{width:82,height:82,borderRadius:24,backgroundColor:'#EFF6FF',alignItems:'center',justifyContent:'center'},logoF:{fontSize:52,fontWeight:'900',color:COLORS.primary},logoCart:{position:'absolute',right:6,bottom:5,fontSize:22},guestTitle:{fontSize:23,fontWeight:'900',marginTop:18},guestSub:{color:COLORS.gray,marginTop:4},login:{backgroundColor:COLORS.primary,borderRadius:13,width:'85%',padding:15,alignItems:'center',marginTop:28},loginText:{color:'#fff',fontWeight:'900'},register:{borderWidth:1,borderColor:COLORS.primary,borderRadius:13,width:'85%',padding:15,alignItems:'center',marginTop:10},registerText:{color:COLORS.primary,fontWeight:'900'},profileHead:{backgroundColor:'#fff',alignItems:'center',paddingTop:25,paddingBottom:22,borderBottomWidth:1,borderBottomColor:'#E5EAF1'},avatar:{width:86,height:86,borderRadius:43,backgroundColor:COLORS.primary,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:36,fontWeight:'900',color:'#fff'},name:{fontSize:22,fontWeight:'900',marginTop:10},phone:{color:COLORS.gray,marginTop:3},rating:{marginTop:6,color:'#64748B',fontWeight:'700'},adminPill:{marginTop:10,backgroundColor:'#ECFDF5',paddingHorizontal:10,paddingVertical:5,borderRadius:20},adminText:{fontSize:10,color:'#15803D',fontWeight:'900'},menu:{backgroundColor:'#fff',marginTop:14},menuItem:{minHeight:70,flexDirection:'row',alignItems:'center',paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:'#EEF2F7'},icon:{fontSize:20,width:36},itemTitle:{fontSize:14,fontWeight:'900',color:COLORS.black},itemSub:{fontSize:10,color:COLORS.gray,marginTop:3},chev:{fontSize:25,color:'#94A3B8'},logout:{marginTop:8}}
);
