export const COLORS = {
  primary: '#2563EB',       // Blue
  primaryDark: '#1D4ED8',
  secondary: '#10B981',     // Green
  accent: '#F59E0B',        // Amber
  background: '#F8FAFC',
  white: '#FFFFFF',
  black: '#0F172A',
  gray: '#64748B',
  lightGray: '#E2E8F0',
  danger: '#EF4444',
  success: '#22C55E',
  card: '#FFFFFF',
  border: '#E2E8F0',
};

export const BRANDS = [
  'Apple',
  'Samsung',
  'Tecno',
  'Infinix',
  'Xiaomi',
  'Oppo',
  'Vivo',
  'Huawei',
  'Nokia',
  'Other',
] as const;

export const CONDITIONS = ['New', 'Like New', 'Good', 'Fair'] as const;

export const NIGERIAN_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa',
  'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo',
  'Ekiti', 'Enugu', 'FCT - Abuja', 'Gombe', 'Imo', 'Jigawa',
  'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
  'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun',
  'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
];

// Simple bilingual texts
export const t = {
  en: {
    home: 'Home',
    search: 'Search',
    sell: 'Sell',
    favorites: 'Favorites',
    profile: 'Profile',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    postPhone: 'Post Phone',
    phoneDetails: 'Phone Details',
    contactSeller: 'Contact Seller',
    call: 'Call',
    whatsapp: 'WhatsApp',
    chat: 'Chat',
    price: 'Price',
    condition: 'Condition',
    location: 'Location',
    description: 'Description',
    brand: 'Brand',
    model: 'Model',
    uploadPhotos: 'Upload Photos',
    submit: 'Submit',
    cancel: 'Cancel',
    noPhones: 'No phones found',
    searchPlaceholder: 'Search phones...',
    welcome: 'Welcome to FULATAN COMMUNICATION',
    sellYourPhone: 'Sell your phone easily',
    buyPhone: 'Buy quality phones',
    myListings: 'My Listings',
    editProfile: 'Edit Profile',
    settings: 'Settings',
    language: 'Language',
    new: 'New',
    likeNew: 'Like New',
    good: 'Good',
    fair: 'Fair',
  },
  ha: {
    home: 'Gida',
    search: 'Nema',
    sell: 'Sayar',
    favorites: 'Abubuwan da aka fi so',
    profile: 'Bayanan kai',
    login: 'Shiga',
    register: 'Yi rajista',
    logout: 'Fita',
    postPhone: 'Saka Wayar',
    phoneDetails: 'Cikakken Bayanin Wayar',
    contactSeller: 'Tuntuɓi Mai Sayarwa',
    call: 'Kira',
    whatsapp: 'WhatsApp',
    chat: 'Hira',
    price: 'Farashi',
    condition: 'Yanayi',
    location: 'Wuri',
    description: 'Bayani',
    brand: 'Alamar',
    model: 'Samfur',
    uploadPhotos: 'Saka Hotuna',
    submit: 'Aika',
    cancel: 'Soke',
    noPhones: 'Babu wayoyi',
    searchPlaceholder: 'Nemo wayoyi...',
    welcome: 'Barka da zuwa FULATAN COMMUNICATION',
    sellYourPhone: 'Sayar da wayarka cikin sauƙi',
    buyPhone: 'Sayi wayoyi masu inganci',
    myListings: 'Jerin na',
    editProfile: 'Gyara Bayanan Kai',
    settings: 'Saituna',
    language: 'Harshe',
    new: 'Sabuwa',
    likeNew: 'Kamar Sabuwa',
    good: 'Mai Kyau',
    fair: 'Matsakaici',
  },
};

export type Language = 'en' | 'ha';
